const htmlContent = {
	en: {
		home: {
			section1: `<h1>Nacim Harfouche</h1>
						<h2>Web Developer</h2>`,
			section2: `<h2 id="home">Home</h2>
						<p style="font-size: 20px; text-align: center"><i class="fas fa-tools"></i> in progress...</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>`
		},
		myProjet: "",
		aboutMe: "",
		contact: ""
	},
	fr: {
		home: {
			section1: `<h1>Nacim Harfouche</h1>
						<h2>Developpeur Web</h2>`,
			section2: `<h2 id="home">Home</h2>
			<p style="font-size: 20px; text-align: center"><i class="fas fa-tools"></i> in progress...</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Iaculis eu non diam phasellus vestibulum. Elit sed vulputate mi sit amet. Diam phasellus vestibulum lorem sed risus. Morbi quis commodo odio aenean sed adipiscing. Elit sed vulputate mi sit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.</p>`
		},
		myProjet: "",
		aboutMe: "",
		contact: ""
	}
}